# Form implementation generated from reading ui file 'C:\Users\Eswaran\Desktop\Python\PyQt5\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_greeting(object):
    def setupUi(self, greeting):
        greeting.setObjectName("greeting")
        greeting.resize(400, 300)
        greeting.setSizeGripEnabled(True)

        self.lName = QtWidgets.QLabel(parent=greeting)
        self.lName.setGeometry(QtCore.QRect(20, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lName.setFont(font)
        self.lName.setScaledContents(True)
        self.lName.setObjectName("lName")

        self.label = QtWidgets.QLabel(parent=greeting)
        self.label.setGeometry(QtCore.QRect(30, 180, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.pushButton_go = QtWidgets.QPushButton(parent=greeting)
        self.pushButton_go.setGeometry(QtCore.QRect(140, 130, 111, 31))
        self.pushButton_go.setObjectName("pushButton_go")

        self.lineEdit_name = QtWidgets.QLineEdit(parent=greeting)
        self.lineEdit_name.setGeometry(QtCore.QRect(160, 50, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setText("")
        self.lineEdit_name.setObjectName("lineEdit_name")

        self.retranslateUi(greeting)
        QtCore.QMetaObject.connectSlotsByName(greeting)

        # Connect button to slot
        self.pushButton_go.clicked.connect(self.update_welcome_message)

    def retranslateUi(self, greeting):
        _translate = QtCore.QCoreApplication.translate
        greeting.setWindowTitle(_translate("greeting", "Dialog"))
        self.lName.setText(_translate("greeting", "Enter Your Name:"))
        self.label.setText(_translate("greeting", "Welcome to our First GUI project !!! "))
        self.pushButton_go.setText(_translate("greeting", "Let's Go"))

    def update_welcome_message(self):
        name = self.lineEdit_name.text()
        self.label.setText(f"Welcome {name}!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    greeting = QtWidgets.QDialog()
    ui = Ui_greeting()
    ui.setupUi(greeting)
    greeting.show()
    sys.exit(app.exec())
